Discord:
  GuildID: 0 # Replace with your guild ID (int)
Twitch:
  Username: "" # Replace with your Twitch username (string)
  ChannelID: 0 # Replace with your channel ID (int) (find it here: https://www.streamweasels.com/tools/convert-twitch-username-to-user-id/)
  ClientID: "0" # Replace with your Twitch app client ID (string) (find it here: https://dev.twitch.tv/console/apps)
